export const BASES = [
  { id: "santa-rosa", nome: "Santa Rosa", sigla: "SR", adm: 10 },
  { id: "tres-passos", nome: "Três Passos", sigla: "TP", adm: 10 },
  { id: "frederico", nome: "Frederico Westphalen", sigla: "FW", adm: 10 },
];

export const INTEGRANTES_POR_TIPO = { "B3": 7, "B2": 4, "B1": 2, "C1": 2, "Polidril": 2, "-": 0 };

export const EQUIPES_POR_BASE = {
  "santa-rosa": [
    {id:"eq1",nome:"SRO 5501",enc:"Paulo",tipo:"B3",meta:25},
    {id:"eq2",nome:"SRO 5363",enc:"Elemar",tipo:"-",meta:0},
    {id:"eq3",nome:"SRO 5823",enc:"João",tipo:"B3",meta:25},
    {id:"eq4",nome:"SRO 5081",enc:"Vanderlei",tipo:"B3",meta:25},
    {id:"eq5",nome:"SRO 5658",enc:"Cleversson",tipo:"B3",meta:25},
    {id:"eq6",nome:"SRO 5838",enc:"Marcio",tipo:"B3",meta:25},
    {id:"eq7",nome:"SRO 5483",enc:"Darci",tipo:"B3",meta:25},
    {id:"eq8",nome:"SRO 5761",enc:"Eloi",tipo:"B3",meta:25},
    {id:"eq9",nome:"SRO 5414",enc:"Lucas",tipo:"B3",meta:25},
    {id:"eq10",nome:"SRO 5839",enc:"Sandro",tipo:"B3",meta:25},
    {id:"eq11",nome:"SRO 6143",enc:"Josias",tipo:"C1",meta:14},
    {id:"eq12",nome:"SRO 6252",enc:"Diecson",tipo:"C1",meta:14},
    {id:"eq13",nome:"SRO 6254",enc:"Reserva",tipo:"-",meta:0},
    {id:"eq14",nome:"SRO 7742",enc:"Reserva",tipo:"-",meta:0},
    {id:"eq15",nome:"SRO 7744",enc:"Polidril",tipo:"Polidril",meta:115.37},
    {id:"eq16",nome:"SRO 7743",enc:"Gilberto",tipo:"B1",meta:18},
    {id:"eq17",nome:"SRO 7745",enc:"Reserva",tipo:"-",meta:0},
    {id:"eq18",nome:"SRO 5502",enc:"Rogério",tipo:"B1",meta:18},
  ],
  "frederico": [
    {id:"eq1",nome:"FWE 5082",enc:"Paulo",tipo:"B3",meta:25},
    {id:"eq2",nome:"FWE 5875",enc:"Adelar",tipo:"B3",meta:25},
    {id:"eq3",nome:"FWE 5893",enc:"Elcindo",tipo:"B3",meta:25},
    {id:"eq4",nome:"FWE 5889",enc:"Nelson",tipo:"B3",meta:25},
    {id:"eq5",nome:"FWE 5840",enc:"Diangro",tipo:"B3",meta:25},
    {id:"eq6",nome:"FWE 5697",enc:"Adejalmo",tipo:"B3",meta:25},
    {id:"eq7",nome:"FWE 5335",enc:"Vagner",tipo:"B3",meta:25},
    {id:"eq8",nome:"FWE 5837",enc:"Altair",tipo:"B3",meta:25},
    {id:"eq9",nome:"FWE 6015",enc:"Amauri",tipo:"C1",meta:14},
    {id:"eq10",nome:"FWE 6549",enc:"Itamar",tipo:"C1",meta:14},
    {id:"eq11",nome:"FWE 7737",enc:"Polidril",tipo:"B1",meta:104.55},
  ],
  "tres-passos": [
    {id:"eq1",nome:"TPA 5698",enc:"Alexandre",tipo:"B3",meta:25},
    {id:"eq2",nome:"TPA 5595",enc:"Tiago",tipo:"B2",meta:16.82},
    {id:"eq3",nome:"TPA 5699",enc:"Ivar",tipo:"B2",meta:16.82},
    {id:"eq4",nome:"TPA 5130",enc:"Ademir",tipo:"B3",meta:25},
    {id:"eq5",nome:"TPA 5883",enc:"Luis O",tipo:"B3",meta:25},
    {id:"eq6",nome:"TPA 5874",enc:"Laercio",tipo:"B3",meta:25},
    {id:"eq7",nome:"TPA 5843",enc:"Deonisio",tipo:"B3",meta:25},
    {id:"eq8",nome:"TPA 5762",enc:"Paulo",tipo:"B2",meta:16.82},
    {id:"eq9",nome:"TPA 6142",enc:"Eder LV",tipo:"C1",meta:14},
    {id:"eq10",nome:"TPA 6003",enc:"Luis LV",tipo:"C1",meta:14},
    {id:"eq11",nome:"TPA 7739",enc:"Giovani",tipo:"B1",meta:104.55},
    {id:"eq12",nome:"TPA 7741",enc:"Luis Prep",tipo:"B1",meta:18},
    {id:"eq13",nome:"TPA 7740",enc:"Dangre Prep",tipo:"B1",meta:18},
  ],
};

export const EQUIPES = EQUIPES_POR_BASE["santa-rosa"];
export const INIT_NOTAS = [];

export const DIAS_UTEIS = 22;
export const DIVISOR_US = 222.67;

export const MOTIVOS_RETRAB = [
  "Calçadas RPS","Calçadas RPE","Poda de vegetação","Estrutura fora de bissetriz",
  "Poste fora do prumo","Recolhimento de resíduos","Aterramento de cerca",
  "Luminária pública","Estrutura diferente do projeto","Tracionamento de cabos",
  "Placa com Nº Operativo","Espaçadores losangulares ou verticais",
  "Ajustar Espaçadores losangulares","Compactar cavas poste velho",
  "Não realizado serviço proposto no projeto","Rede locada em local errado",
  "Cabos de telefone","Outro"
];

export const SERVICOS_LISTA = [
  {id:"s1",d:"INSTALAÇÃO DE POSTE",v:556.68},
  {id:"s2",d:"RETIRADA DE POSTE",v:400.81},
  {id:"s3",d:"LANÇAMENTO DE CABO",v:712.54},
  {id:"s4",d:"INSTALAÇÃO DE ESTRUTURA",v:445.34},
  {id:"s5",d:"RETIRADA DE ESTRUTURA",v:334.01},
  {id:"s6",d:"INSTALAÇÃO DE LUMINÁRIA",v:222.67},
  {id:"s7",d:"RETIRADA DE LUMINÁRIA",v:178.14},
  {id:"s8",d:"PODA DE VEGETAÇÃO",v:267.20},
  {id:"s9",d:"ATERRAMENTO",v:623.48},
  {id:"s10",d:"TRACIONAMENTO",v:489.87},
  {id:"s11",d:"INSTALAÇÃO DE ESPAÇADOR",v:111.34},
  {id:"s12",d:"INSTALAÇÃO DE ESTAI",v:400.81},
  {id:"s13",d:"REGULAGEM DE FLECHA",v:334.01},
  {id:"s14",d:"CALÇADA/PASSEIO",v:668.01},
  {id:"s15",d:"CONEXÃO/EMENDA",v:222.67},
  {id:"s16",d:"INSTALAÇÃO DE PLACA",v:66.80},
  {id:"s17",d:"COMPACTAÇÃO DE CAVA",v:178.14},
  {id:"s18",d:"OUTRO",v:0},
];

export const FUNCIONARIOS = {
  "santa-rosa": [
    {eq:"SRO5501",re:"3937",nome:"PAULO CESAR STEINBORN",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5501",re:"5936",nome:"JONATHAN MIRANDA DE SOUZA",fn:"ELETRICISTA"},
    {eq:"SRO5501",re:"6101",nome:"NATHAN PADILHA JUNGES",fn:"ELETRICISTA"},
    {eq:"SRO5501",re:"7030",nome:"EVERTON TURCOT",fn:"ELETRICISTA"},
    {eq:"SRO5501",re:"7301",nome:"DOUGLAS LIPES DE OLIVEIRA",fn:"SERVENTE"},
    {eq:"SRO5501",re:"7422",nome:"EVERTON HOFFERBER LERMEN",fn:"SERVENTE"},
    {eq:"SRO5823",re:"883",nome:"JOAO ALCINDO DOS SANTOS DURAO",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5823",re:"5905",nome:"JOAO CARLOS DA SILVA AQUINO",fn:"ELETRICISTA"},
    {eq:"SRO5823",re:"6103",nome:"ROINEL JOSE RAMOS",fn:"ELETRICISTA"},
    {eq:"SRO5823",re:"6523",nome:"DENILSON FERNANDO MACHADO",fn:"ELETRICISTA"},
    {eq:"SRO5823",re:"7418",nome:"CESAR NAHUEL VELAZQUEZ",fn:"SERVENTE"},
    {eq:"SRO5823",re:"7643",nome:"ISAEL BALDAIR FERREIRA",fn:"SERVENTE"},
    {eq:"SRO5483",re:"3435",nome:"DARCI STEFAN",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5483",re:"5798",nome:"EDERSON WROBEL",fn:"ELETRICISTA"},
    {eq:"SRO5483",re:"6658",nome:"FRANCISCO SANTIAGO GALARCE",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5483",re:"6958",nome:"LEONARDO MICAEL DE SOUZA",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5483",re:"7028",nome:"OTAVIO OLIVEIRA MACHADO",fn:"SERVENTE"},
    {eq:"SRO5483",re:"7836",nome:"ADRIANO ALCINE SCHONINGER",fn:"SERVENTE"},
    {eq:"SRO5081",re:"7088",nome:"VANDERLEI DA SILVA PAQUEIRA",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5081",re:"5434",nome:"RAUL VICENTE LIPSKI LEMOS",fn:"ELETRICISTA"},
    {eq:"SRO5081",re:"6883",nome:"ALISSON MATTOS AQUINO",fn:"ELETRICISTA"},
    {eq:"SRO5081",re:"7425",nome:"JONATAS MISAEL DA SILVA",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5081",re:"7646",nome:"WESLEY FERNANDO DE OLIVEIRA LEITE",fn:"SERVENTE"},
    {eq:"SRO5414",re:"4358",nome:"LUCAS NEU",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5414",re:"6777",nome:"JOAO VITOR FREITAS MACHADO",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5414",re:"4978",nome:"LUCAS FELDMANN",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5414",re:"7302",nome:"FERNANDO KLAT BUENO",fn:"AUXILIAR DE ELETRICISTA TRAINEE"},
    {eq:"SRO5414",re:"7274",nome:"MOISES FERNANDO DA SILVA CORREA",fn:"AUXILIAR DE ELETRICISTA TRAINEE"},
    {eq:"SRO5414",re:"7419",nome:"CHARLES JUNIOR RODRIGUES",fn:"SERVENTE"},
    {eq:"SRO5761",re:"7161",nome:"ELOI DE MOURA PAVAO",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5761",re:"7115",nome:"TIAGO DO CARMO DE PAYVA",fn:"ELETRICISTA"},
    {eq:"SRO5761",re:"7571",nome:"JORGE ANTONIO KIELING",fn:"ELETRICISTA"},
    {eq:"SRO5761",re:"7423",nome:"FELIPE MOREIRA",fn:"SERVENTE"},
    {eq:"SRO5761",re:"7860",nome:"FABRICIO MIKAEL FERREIRA CARVALHO",fn:"SERVENTE"},
    {eq:"SRO5658",re:"7132",nome:"CLEVERSON DO CARMO DE PAYVA/ Osmar",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5658",re:"6469",nome:"VANDERLEI PEREIRA DO NASCIMENTO",fn:"ELETRICISTA"},
    {eq:"SRO5658",re:"6098",nome:"JORGE CARLOS SILVA DOS SANTOS",fn:"ELETRICISTA"},
    {eq:"SRO5658",re:"5099",nome:"JOAO LUCAS SANTOS SILVA",fn:"ELETRICISTA"},
    {eq:"SRO5658",re:"7186",nome:"JOAO LUIZ SEVERO",fn:"SERVENTE"},
    {eq:"SRO5839",re:"7471",nome:"SANDRO KUZEY",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"SRO5839",re:"6381",nome:"HECTOR RAMON RODRIGUEZ",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5839",re:"5640",nome:"VINICIUS RIBEIRO DA SILVA",fn:"ELETRICISTA"},
    {eq:"SRO5839",re:"7645",nome:"HENTONY WILLIAM AGAPIO ORTIZ",fn:"SERVENTE"},
    {eq:"SRO5838",re:"7878",nome:"MARCIO JURAWSKI",fn:"ENCARREGADO"},
    {eq:"SRO5838",re:"7861",nome:"NILTON DE OLIVEIRA JUNIOR",fn:"ELETRICISTA"},
    {eq:"SRO5838",re:"5306",nome:"MOACIR DOS SANTOS COSTA",fn:"ELETRICISTA"},
    {eq:"SRO5838",re:"7862",nome:"OSIEL HATWIG DA SILVA",fn:"SERVENTE"},
    {eq:"SRO5838",re:"7083",nome:"ALDAIR ALEXANDRE DREWS",fn:"SERVENTE"},
    {eq:"SRO6143",re:"3756",nome:"JOSIAS DA SILVA GODOY",fn:"ELETRICISTA LV"},
    {eq:"SRO6143",re:"6473",nome:"RICARDO MARCELO CAYETANO ESTANDER",fn:"ELETRICISTA LV TRAINEE"},
    {eq:"SRO6143",re:"7152",nome:"LEONARDO GENRO DE OLIVEIRA",fn:"ELETRICISTA LV TRAINEE"},
    {eq:"SRO6252",re:"4104",nome:"DIECSON BATISTA PEREIRA",fn:"ELETRICISTA LV"},
    {eq:"SRO6252",re:"4713",nome:"NATHAN FAGUNDES MOELLMANN",fn:"ELETRICISTA LV"},
    {eq:"SRO7743",re:"6422",nome:"GILBERTO REICHEL DO NASCIMENTO",fn:"ELETRICISTA"},
    {eq:"SRO7743",re:"7250",nome:"JUARES ALMEIDA",fn:"SERVENTE"},
    {eq:"SRO7743",re:"7477",nome:"CESAR LUIS RODRIGUES",fn:"SERVENTE"},
    {eq:"SRO5502",re:"2777",nome:"ROGERIO SCHUCK",fn:"AUXILIAR DE ELETRICISTA"},
    {eq:"SRO5502",re:"7470",nome:"TIAGO MATEUS SEIBERT",fn:"SERVENTE"},
    {eq:"SRO5502",re:"7644",nome:"VICTOR ARCENIO MAY",fn:""},
    {eq:"ADM",re:"6663",nome:"GABRIEL PAULOS",fn:"GERENTE OPERACIONAL"},
    {eq:"ADM",re:"869",nome:"JOSEMAR HACK",fn:"SUPERVISOR"},
    {eq:"ADM",re:"1664",nome:"OSMAR LUIS KIELING",fn:"ENCARREGADO DE EQUIPE"},
    {eq:"ADM",re:"5795",nome:"ALEXANDRE AIRTON DA SILVA",fn:"AUXILIAR DE ELETRICISTA ( EPI )"},
    {eq:"ADM",re:"6362",nome:"VITORIA DA COSTA VOLKWEIS",fn:"AUXILIAR ADMINSTRATIVO"},
    {eq:"ADM",re:"6592",nome:"VICTOR IVO VIANA",fn:"AUXILIAR ADMINSTRATIVO"},
    {eq:"ALMOX",re:"6639",nome:"DANIEL DUARTE DE OLIVEIRA",fn:"AUXILIAR DE ALMOXARIFADO"},
    {eq:"ALMOX",re:"7177",nome:"DIEGO RAFAEL PEREIRA MARTINS",fn:"AUXILIAR DE ALMOXARIFADO"},
    {eq:"ALMOX",re:"7600",nome:"CHARLES GAELZER",fn:"AUXILIAR DE ALMOXARIFADO"},
    {eq:"PATIO",re:"6443",nome:"LOURENCO MACIEL MACHADO",fn:"AUXILIAR DE PATIO"},
    {eq:"PATIO",re:"7390",nome:"NILTON SERGIO DE FREITAS DE OLIVEIRA",fn:"SERVENTE (posto)"},
  ],
  "tres-passos": [],
  "frederico": [],
};

export const VEICULOS = {
  "ADM": {placa:"IZX8A52",marca:"",guindaste:""},
  "SRO5081": {placa:"JBO2G50",marca:"IVECO",guindaste:"PALFINGER 17.000"},
  "SRO5414": {placa:"JAD2E49",marca:"IVECO",guindaste:"ARGOS 20.5"},
  "SRO5483": {placa:"JBA2H75",marca:"COSTELLATION",guindaste:"ARGOS 20.5"},
  "SRO5501": {placa:"JDL2G75",marca:"COSTELLATION",guindaste:"MASAL"},
  "SRO5502": {placa:"IZA-6I12",marca:"FORD",guindaste:"ARGOS 20.6"},
  "SRO5658": {placa:"IYY6903",marca:"FORD",guindaste:"ARGOS 20.5"},
  "SRO5761": {placa:"JAG0F42",marca:"IVECO",guindaste:"ARGOS 12.5"},
  "SRO5823": {placa:"JBG7D86",marca:"COSTELLATION",guindaste:"PALFINGER 23.000"},
  "SRO5838": {placa:"JBO9B97",marca:"IVECO",guindaste:"PALFINGER 17.000"},
  "SRO5839": {placa:"IYX1898",marca:"FORD",guindaste:"ARGOS 20.5"},
  "SRO6143": {placa:"IZZ6A13",marca:"IVECO",guindaste:"MASAL"},
  "SRO6252": {placa:"IYX0585",marca:"FORD",guindaste:"MASAL"},
  "SRO7743": {placa:"IUL1160",marca:"COSTELLATION",guindaste:"PALFINGER 15.500"}
};
